version: '3.7'

services:
#  send_files:
#    environment:
#      - MONGO_URL=mongodb://db:27017
#    build:
#      context: .
#      dockerfile: ./Send_files/Dockerfile
#    ports:
#      - "8000:8000"
#  scan_files:
#    environment:
#      - MONGO_URL=mongodb://db:27017
#    build:
#      context: .
#      dockerfile: ./Scan_files/Dockerfile
#    ports:
#      - "8001:8001"
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: db
    volumes: 
      - ./mongo_data:/data/db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis
    hostname: redis
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml